# Generated by Django 3.2.5 on 2021-08-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_phone'),
        ('comments', '0002_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replyuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='topcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_comment', to='comments.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user'),
        ),
    ]
