# Generated by Django 3.2.5 on 2021-08-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_phone'),
        ('comments', '0003_auto_20210808_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='replyuser',
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='replycomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='comments.comments'),
        ),
    ]
