# Generated by Django 3.2.5 on 2021-08-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_phone'),
        ('comments', '0004_auto_20210808_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reply_user',
            new_name='replyuser',
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='user.user'),
        ),
    ]
