# Generated by Django 3.2.5 on 2021-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_id',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('name',), name='user'),
        ),
    ]
