# Generated by Django 3.2.5 on 2021-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210724_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagepath',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
