# Generated by Django 3.2.5 on 2021-08-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='110', max_length=128),
            preserve_default=False,
        ),
    ]
