# Generated by Django 3.2.5 on 2021-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other',
            name='age',
            field=models.CharField(default='1', max_length=4),
            preserve_default=False,
        ),
    ]
